name: .NET CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_dotnet:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1 
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: Backend/TeamVas
    - name: Build
      run: dotnet build --no-restore
      working-directory: Backend/TeamVas
  unittest_dotnet:
    needs: build_dotnet
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test
      run: dotnet test --no-build --verbosity normal .TeamVas.Tests/TeamVas.Tests.csproj
      working-directory: Backend/TeamVas
      
  build_and_push_docker:
    needs: unittest_dotnet # This job depends on the successful completion of the build_dotnet job
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2 
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./Backend/TeamVas
        file: ./Backend/TeamVas/Dockerfile.ci
        push: true
        tags: billyyy/teamvas
