name: SonarQube 

on:
  push:
    branches:
      - main

jobs:
  sonarqube-analysis-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Install SonarScanner
        run: dotnet tool install --global dotnet-sonarscanner --version 5.14.0

      - name: Install dotnet-coverage
        run: dotnet tool install -g dotnet-coverage

      - name: Run SonarQube Analysis
        working-directory: ./Backend/TeamVas
        run: |
          dotnet sonarscanner begin /k:"Teamvas_backend" /d:sonar.host.url="${{ secrets.SONAR_HOST_URL }}" /d:sonar.token="${{ secrets.SONAR_TOKEN_BACKEND }}"
          dotnet build 
          dotnet sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN_BACKEND }}"

  sonarqube-analysis-frontend:
    runs-on: ubuntu-latest
    permissions: read-all
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16
      
      - name: Restore dependencies
        run: |
          yarn install
          working-directory: ./Backend/TeamVas
      
      - name: SonarQube Analysis
        uses: sonarsource/sonarqube-scan-action@master
        with:
          projectBaseDir: ./Backend/TeamVas
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_FRONTEND }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
